name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main
            
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.12'  # must match the Jupyter kernel julia-1.12 used by the .qmd files
      - run: |
          julia --project -e 'using Pkg;
                              Pkg.add("Suppressor");
                              Pkg.add("IJulia");
                              Pkg.build("IJulia");
                              using IJulia;
                              Pkg.instantiate()'
      - run: quarto check jupyter
      
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
